### ISSUE TITLE
exception when executing impex via console

### ISSUE THREAD

**Issue by amddsc** [epam/sap-commerce-intellij-idea-plugin#1017]
when i try to execute impex from console I get the following exception:

`java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.intellij.idea.plugin.hybris.tools.remote.console.impl.HybrisImpexConsole.getRequestParams(HybrisImpexConsole.kt:98)
	at com.intellij.idea.plugin.hybris.tools.remote.console.impl.HybrisImpexConsole.execute(HybrisImpexConsole.kt:84)
	at com.intellij.idea.plugin.hybris.tools.remote.console.actions.handler.HybrisConsoleExecuteActionHandler$processLine$1$1.run(HybrisConsoleExecuteActionHandler.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
`

Intellij Ultimate 2023.3.4
SAP Commerce Developer Toolset 2023.3.4
SAP Commerce 2205.21

Intellij and Commerce running in ubuntu WSL

**Comment by mlytvyn** [comment]
@amddsc , thank you for highlighting this, it is already fixed in the next release for Idea 2024.1, but I will release a tiny hot fix release for Idea 2023 just to not force Idea upgrade if not needed.

stay tuned.

**Comment by amddsc** [comment]
Oh sorry, I wasn't aware of this. Thanks for your effort.

Regards,
Alex

**Comment by mlytvyn** [comment]
@amddsc , there is nothing to say sorry for! thank you very much for your feedback and using the plugin!

if you have any suggestions or ideas feel free to create new GitHub issue :)

**Comment by mlytvyn** [comment]
@amddsc new version has been released, please re-check

**Comment by amddsc** [comment]
Yes, works fine now. Thank you so much!
