### ISSUE TITLE
SAP Commerce Plugin 2024.3.1 break normal Unit Tests

### ISSUE THREAD

**Issue by marvin-w** [epam/sap-commerce-intellij-idea-plugin#1283]
After upgrading my IDEA to 2024.3 and in return the SAP Commerce Plugin to 2024.3.1 I noticed that I was unable to run (some) unit tests through IntelliJ.

It kept failing on me with the following stacktrace:

```java
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/marvin/source/xyz/xyz-hybris/core-customize/hybris/bin/platform/ext/core/lib/log4j-slf4j-impl-2.21.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/marvin/source/xyz/xyz-hybris/core-customize/hybris/bin/custom/namcontentsearch/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
 
de.hybris.bootstrap.config.BootstrapConfigException: Neither /home/marvin/source/xyz/xyz-hybris/core-customize/hybris/bin/custom/xyzcore/=/home/marvin/source/xyz/xyz-hybris/core-customize/hybris/config/localextensions.xml nor /home/marvin/source/xyz/xyz-hybris/core-customize/hybris/bin/custom/xyzcore/=/home/marvin/source/xyz/xyz-hybris/core-customize/hybris/bin/platform/extensions.xml found!
 
	at de.hybris.bootstrap.config.PlatformConfig.determineExtensionsFile(PlatformConfig.java:182)
	at de.hybris.bootstrap.config.PlatformConfig.collectConfiguredExtensions(PlatformConfig.java:948)
	at de.hybris.bootstrap.config.PlatformConfig.<init>(PlatformConfig.java:135)
	at de.hybris.bootstrap.config.PlatformConfig.getInstance(PlatformConfig.java:124)
	at de.hybris.bootstrap.config.ConfigUtil.getPlatformConfig(ConfigUtil.java:641)
	at de.hybris.platform.util.Utilities.assureCoreUtilities(Utilities.java:221)
	at de.hybris.platform.util.Utilities.loadPlatformProperties(Utilities.java:2716)
	at de.hybris.platform.util.logging.log4j2.HybrisLog4j2ConfigurationFactory.getConfiguration(HybrisLog4j2ConfigurationFactory.java:48)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:411)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:318)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:690)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:61)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at com.xyz.xyz.hybris.core.xyz.services.impl.xyz.<init>(xyz.java:46)
	at com.xyz.xyz.hybris.core.xyz.services.impl.xyz.setUp(xyz.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

It also created this weird looking directory structure in the module I was trying to execute unit tests for:

![image](https://github.com/user-attachments/assets/d0e0f4b9-3785-4cb0-8db9-0538e0833c83)

Ultimately, I downgraded again to 2024.2 and everything is working again.

I think it might be related to this change: https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/1241/files 

Hope it helps and thanks for this awesome plugin <3.

**Comment by mlytvyn** [comment]
@marvin-w , most probably, to be fixed in the next release with the https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/1279
@StefanKruk fyi

**Comment by marvin-w** [comment]
@mlytvyn Ah cool thanks! Do you already have an ETA on the next release?

**Comment by mlytvyn** [comment]
@marvin-w , hidden, so far, you can try to install it manually
https://plugins.jetbrains.com/plugin/12867-sap-commerce-developers-toolset/versions/stable/639711?noRedirect=true

**Comment by mlytvyn** [comment]
@marvin-w , can you please try with the latest released version `2024.3.2` ?

**Comment by mlytvyn** [comment]
@marvin-w , can you re-check it please?

p.s. happy new year!

**Comment by marvin-w** [comment]
@marvin-w works fine now, thanks!

happy new year and thanks again!
