### ISSUE TITLE
Eclipse install issue

### ISSUE THREAD

**Issue by joebodo** [epam/sap-commerce-intellij-idea-plugin#15]
Attempting to install the plugin from the marketplace gives:

Unable to read repository at http://www.epam.com/content/dam/epam/eclipse/content.xml.

![Screen Shot 2021-04-10 at 11 38 11 AM](https://user-images.githubusercontent.com/1405002/114279329-493f8600-99f1-11eb-9629-efadaad5f3e2.jpg)

**Comment by ghost** [comment]
Hello, could you provide an Error Log?

**Comment by kepler155c** [comment]
This URL does not seem to be valid anymore: https://www.epam.com/content/dam/epam/eclipse/content.xml

```!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 2021-04-11 17:16:00.473
!MESSAGE Unable to read repository at http://www.epam.com/content/dam/epam/eclipse/compositeContent.xml.
!STACK 0
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:248)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.http.client.CircularRedirectException: Circular redirect to 'https://www.epam.com/404.html'
	at org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:190)
	at org.apache.http.impl.client.DefaultRedirectStrategy.getRedirect(DefaultRedirectStrategy.java:220)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:121)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	... 4 more```

**Comment by ghost** [comment]
@joebodo , @kepler155c 
Looks like this issue relates to the plugin for Eclipse IDE. Instead, the current repository dedicated to the plugin for IntelliJ IDEA.

**Comment by kepler155c** [comment]
Is there a repo for the eclipse version ? i am unable to find it - thx

**Comment by ghost** [comment]
As far as I know, there is not any public repo for the eclipse version and no support provides.

**Comment by kepler155c** [comment]
ok - thank you
