### ISSUE TITLE
Wrong range in reference in Impex files in case of header Type or Columns changes

### ISSUE THREAD

**Issue by narendramathuriya31** [epam/sap-commerce-intellij-idea-plugin#196]
Env:
IntelliJ IDEA 2022.3.2 (Community Edition)
Build #IC-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2024M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.properties.bundle.editor (223.7571.203)
    com.nnthink.aixcoder (4.1.11-2020)
    **com.intellij.idea.plugin.sap.commerce (2022.3.0)**
    org.sonarlint.idea (7.4.0.60471)

Kotlin: 223-1.8.0-release-345-IJ8617.56

Stacktrace:

Wrong range in reference com.intellij.idea.plugin.hybris.impex.psi.references.TypeSystemAttributeReference(ImpexAnyHeaderParameterNameImpl(ANY_HEADER_PARAMETER_NAME):(0,11)): (0,11). Reference text: 'startRange'

java.lang.StringIndexOutOfBoundsException: begin 0, end 11, length 10
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at com.intellij.openapi.util.TextRange.substring(TextRange.java:103)
	at com.intellij.psi.PsiReferenceBase.getValue(PsiReferenceBase.java:71)
	at com.intellij.psi.PsiReferenceBase.getCanonicalText(PsiReferenceBase.java:101)
	at com.intellij.idea.plugin.hybris.impex.inspection.ImpexHeaderLineVisitor.visitAnyHeaderParameterName(UnknownTypeAttributeInspection.kt:51)
	at com.intellij.idea.plugin.hybris.impex.psi.impl.ImpexAnyHeaderParameterNameImpl.accept(ImpexAnyHeaderParameterNameImpl.java:21)
	at com.intellij.idea.plugin.hybris.impex.psi.impl.ImpexAnyHeaderParameterNameImpl.accept(ImpexAnyHeaderParameterNameImpl.java:26)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$9(InspectionRunner.java:324)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:332)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:338)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:301)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:301)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:299)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:284)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:272)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by mlytvyn** [comment]
@narendramathuriya31 , can you please share sample impex file for which you're facing this error?

**Comment by mlytvyn** [comment]
@narendramathuriya31 , I was able to reproduce it locally, will try to prepare a fix during this week so it can be included in the nearest release

**Comment by mlytvyn** [comment]
root cause fixed for Impex and FlexibleSearch files.
