### ISSUE TITLE
ClassNotFoundException for ImpexHeaderHighlighterComponent on IDE startup - Using Ultimate Intellij 2022.3

### ISSUE THREAD

**Issue by daychissaf** [epam/sap-commerce-intellij-idea-plugin#207]
Using Ultimate Intellij 2022.3, I get ClassNotFoundException for ImpexHeaderHighlighterComponent on IDE startup

`Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.diagnostic.PluginException: Fatal error initializing '
                com.intellij.idea.plugin.hybris.impex.assistance.ImpexHeaderHighlighterComponent
            ' [Plugin: ccom.intellij.idea.plugin.commerce.integration]
    at com.intellij.serviceContainer.ComponentManagerImpl.handleInitComponentError$intellij_platform_serviceContainer(ComponentManagerImpl.kt:571)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:382)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:50)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:260)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
    at com.intellij.idea.ApplicationLoader.doInitApplication(ApplicationLoader.kt:78)
    at com.intellij.idea.ApplicationLoader.access$doInitApplication(ApplicationLoader.kt:1)
    at com.intellij.idea.ApplicationLoader$doInitApplication$1.invokeSuspend(ApplicationLoader.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:61)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at com.intellij.idea.p.p(p.java:69)
    at com.intellij.ide.p.a.e.p(e.java:135)
    at com.intellij.ide.p.a.p2.p(p2.java:191)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at com.intellij.idea.MainImpl.start(MainImpl.kt:60)
    at com.intellij.idea.StartupUtil$startApplication$7.invokeSuspend(StartupUtil.kt:298)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.Main.main(Main.kt:36)
Caused by: java.lang.ClassNotFoundException: 
                com.intellij.idea.plugin.hybris.impex.assistance.ImpexHeaderHighlighterComponent
             PluginClassLoader(plugin=PluginDescriptor(name=Integration for SAP Commerce, id=ccom.intellij.idea.plugin.commerce.integration, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.3/Integration-SAP-Commerce, version=2019.1, package=null, isBundled=false), packagePrefix=null, instanceId=354, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:217)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:495)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:374)
    ... 33 more

-----
Your JRE: 17.0.5+1-b653.25 amd64 (JetBrains s.r.o.)
/snap/intellij-idea-ultimate/405/jbr`

**Comment by mlytvyn** [comment]
@daychissaf , please ensure that you have only EPAM's plugin installed (https://plugins.jetbrains.com/plugin/12867-sap-commerce-developers-toolset).

And update to the latest version of the plugin as your version 2019.1 is not compatible with IDEA 2022.3.

**Comment by daychissaf** [comment]
Even if we use 2019.2 version, it doesn't work. I have the same error.
I had to choose the plugin 'SAP Commerce Developers Toolset (https://plugins.jetbrains.com/plugin/12867-sap-commerce-developers-toolset)' instead of 'Integration for SAP Commerce' and it works fine.

Thank you
