### ISSUE TITLE
Cannot refresh CCv2 Project

### ISSUE THREAD

**Issue by szzsa** [epam/sap-commerce-intellij-idea-plugin#305]
IDEA version: **2023.1** (Build #IU-231.8109.175, built on March 28, 2023)
Plugin version: **2023.1.2** (built on Mar 27, 2023)

When trying to refresh the SAP Hybris project the plugin gives the following  stack trace:

java.lang.IllegalStateException: @NotNull method com/intellij/idea/plugin/hybris/project/descriptors/DefaultHybrisProjectDescriptor.getPlatformHybrisModuleDescriptor must not return null
	at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.$$$reportNull$$$0(DefaultHybrisProjectDescriptor.java)
	at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.getPlatformHybrisModuleDescriptor(DefaultHybrisProjectDescriptor.java:735)
	at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultJavaCompilerConfigurator.findBuildCompilerProperty(DefaultJavaCompilerConfigurator.java:69)
	at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultJavaCompilerConfigurator.configure(DefaultJavaCompilerConfigurator.java:31)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.configureJavaCompiler(ImportProjectProgressModalWindow.java:299)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.run(ImportProjectProgressModalWindow.java:218)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mlytvyn** [comment]
@szzsa , please provide plugin and Intellij IDEA version, also describe folder structure for the project.

have you tried re-importing project from the scratch?

**Comment by szzsa** [comment]
@mlytvyn Description updated. I didn't try importing project from scratch yet. Will keep you updated about that.

**Comment by mlytvyn** [comment]
latest version of the Plugin had some crucial API changes and it could lead to issues with projects imported with older versions of the Plugin.
Maybe you remember what was your previous version of the Plugin?

**Comment by szzsa** [comment]
My previous plugin version was 2022.3.1

**Comment by szzsa** [comment]
UPDATE: Managed to import the project from scratch by selecting the option _"Scan for SAP Commerce modules even in external modules i.e. eclipse. (slower import/refresh)"_

**Comment by mlytvyn** [comment]
@szzsa, works for test setup, I've just tried to reproduce it by following these steps:
1. Created new project for SAP Commerce 2211
2. Generated new set of `training` extensions with `modulegen`
3. Imported Project with Plugin 2022.3.1 and IDEA 2022.3
4. Closed IDEA
5. Opened the Project in IDEA 2023.1
6. Refreshed the Project with latest Plugin 2023.1.2

could you please share details of our Project Folder Structure & SAP Commerce version? Please take into consideration that usually I'm working on "training" sample projects to omit any legal issues.

**Comment by szzsa** [comment]
@mlytvyn My Hybris installation is in _[PROJECT_ROOT]/core-customize/hybris_ folder.
Maybe this issue is related: https://plugins.jetbrains.com/plugin/12867-sap-commerce-developers-toolset/reviews#review=61164

**Comment by mlytvyn** [comment]
@szzsa , I'm afraid that it may be insufficient, would you be able to describe project structure in more details so I can reproduce it locally?

p.s. yes, it may be related, not easy to handle all possible project setups.

**Comment by szzsa** [comment]
@mlytvyn Besides the location of the installation directory, the custom extensions are grouped into folders inside bin/custom (e.g. bin/custom/myparentfolder/mycustomextension). These are the main differences from a standard sample project structure.

**Comment by mlytvyn** [comment]
@szzsa , yup, was able to reproduce (even initial import does not work well), will look to it tomorrow. No guarantees so far that it will be fixed soon, but I'll do my best; stay tuned!

<img width="252" alt="image" src="https://user-images.githubusercontent.com/2292510/228351233-4c80e33f-8d05-46b4-969c-2c38f12c69f5.png">

**Comment by szzsa** [comment]
@mlytvyn Thank you for your fast response and support. Until a fix the workaround is this:

> UPDATE: Managed to import the project from scratch by selecting the option _"Scan for SAP Commerce modules even in external modules i.e. eclipse. (slower import/refresh)"_

**Comment by szzsa** [comment]
UPDATE: My so called workaround didn't really work. The module dependencies are not correctly imported (e.g. generated model classes are not in the classpath).

**Comment by mlytvyn** [comment]
@szzsa , it seems to be very old issue and will require some time to find out a solution. Meanwhile you can try more common folder structure, maybe with some symbolic links.

as always, feel free to contribute!

**Comment by sigiswald** [comment]
Same issue over here when I upgraded both IntelliJ and the plugin to the latest version a few hours ago. The versions are the same as mentioned in this post and so is the project structure.

Thanks for the support!

**Comment by mlytvyn** [comment]
@szzsa , @sigiswald , yeah, it seems to be due support of CCv2 modules and that specific project structure.

I'll try to push change today and will request release later this week.

----
it would be ideal to not place platform under `core-customize`, instead play around with symbolic links.

Sample of the working project structure:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/2292510/228664681-cc2ad900-e8a2-40a5-a39f-aa2d2ede500a.png">

and it will result into something like that:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/2292510/228665203-bfc09771-05a4-4e37-88ad-fba9e84fe010.png">

**Comment by mlytvyn** [comment]
@szzsa , @sigiswald , please try with latest release https://plugins.jetbrains.com/plugin/12867-sap-commerce-developers-toolset/versions/stable/313809

**Comment by sigiswald** [comment]
@mlytvyn THANK YOU so much for releasing the fix so fast!!!
