### ISSUE TITLE
Wrong range in reference com.intellij.idea.plugin.hybris.impex.psi.references.TypeSystemAttributeReference(ImpexAnyHeaderParameterNameImpl(ANY_HEADER_PARAMETER_NAME):(0,12)): (0,12). Reference text: 'name'

### ISSUE THREAD

**Issue by albert-lau-sap** [epam/sap-commerce-intellij-idea-plugin#33]
This happens when I switch to a different git branch.

Wrong range in reference com.intellij.idea.plugin.hybris.impex.psi.references.TypeSystemAttributeReference(ImpexAnyHeaderParameterNameImpl(ANY_HEADER_PARAMETER_NAME):(0,12)): (0,12). Reference text: 'name'

java.lang.StringIndexOutOfBoundsException: begin 0, end 12, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.intellij.openapi.util.TextRange.substring(TextRange.java:103)
	at com.intellij.psi.PsiReferenceBase.getValue(PsiReferenceBase.java:71)
	at com.intellij.psi.PsiReferenceBase.getCanonicalText(PsiReferenceBase.java:101)
	at com.intellij.idea.plugin.hybris.impex.inspection.ImpexHeaderLineVisitor.visitAnyHeaderParameterName(UnknownTypeAttributeInspection.kt:51)
	at com.intellij.idea.plugin.hybris.impex.psi.impl.ImpexAnyHeaderParameterNameImpl.accept(ImpexAnyHeaderParameterNameImpl.java:21)
	at com.intellij.idea.plugin.hybris.impex.psi.impl.ImpexAnyHeaderParameterNameImpl.accept(ImpexAnyHeaderParameterNameImpl.java:26)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:64)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:352)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:352)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by ghost** [comment]
This issue is quite long is open, is it still reproducible?

**Comment by mlytvyn** [comment]
@albert-lau-sap , should be fixed in 2022.3.1
