### ISSUE TITLE
Getting an IDE Error

### ISSUE THREAD

**Issue by Debagnik** [epam/sap-commerce-intellij-idea-plugin#365]
Hi
I am getting an IDE Error every time I open SAP Hybris project on IntelliJ

`Items validation error. File: <projectname>core-items.xml

java.lang.NullPointerException
	at com.intellij.idea.plugin.hybris.system.type.validation.impl.ItemsFileValidation.findAllInheritClasses(ItemsFileValidation.kt:125)
	at com.intellij.idea.plugin.hybris.system.type.validation.impl.ItemsFileValidation.isFileOutOfDateWithGeneratedClasses(ItemsFileValidation.kt:83)
	at com.intellij.idea.plugin.hybris.system.type.validation.impl.ItemsFileValidation.isFileOutOfDate(ItemsFileValidation.kt:50)
	at com.intellij.idea.plugin.hybris.startup.ItemsXmlFileOpenStartupActivity$execute$task$1.run$lambda$1(ItemsXmlFileOpenStartupActivity.kt:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.idea.plugin.hybris.startup.ItemsXmlFileOpenStartupActivity$execute$task$1.run(ItemsXmlFileOpenStartupActivity.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)`

This is the stack trace. any help would be appreciated

**Comment by mlytvyn** [comment]
Hello, @Debagnik , thank you for reporting this issue, it has been fixed in scope of the https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/360.

Please wait for release `2023.1.5`
