### ISSUE TITLE
java.lang.NumberFormatException: For input string: "0-M308"

### ISSUE THREAD

**Issue by KakaWangSAP** [epam/sap-commerce-intellij-idea-plugin#38]
java.lang.NumberFormatException: For input string: "0-M308"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.intellij.idea.plugin.hybris.common.Version.parseVersion(Version.java:84)
	at com.intellij.idea.plugin.hybris.common.services.impl.DefaultCommonIdeaService.is2019plus(DefaultCommonIdeaService.kt:168)
	at com.intellij.idea.plugin.hybris.common.services.impl.DefaultCommonIdeaService.getBackofficeWebInfLib(DefaultCommonIdeaService.kt:173)
	at com.intellij.idea.plugin.hybris.project.descriptors.RegularHybrisModuleDescriptor.getLibraryDescriptors(RegularHybrisModuleDescriptor.java:316)
	at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultLibRootsConfigurator.configure(DefaultLibRootsConfigurator.java:73)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.run(ImportProjectProgressModalWindow.java:229)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ghost** [comment]
Hello, @KakaWangSAP, please provide the full version name of your SAP Commerce distributive

**Comment by KakaWangSAP** [comment]
Hi Mykyta,

I’m from SAP Commerce product develop team, which means the version of commerce I used is the upcoming(not released) version.


Best regards,
Wang Kaka

From: Mykyta Kostiuk ***@***.***>
Date: Friday, December 24, 2021 at 4:20 AM
To: epam/sap-commerce-intellij-idea-plugin ***@***.***>
Cc: Wang, Kaka ***@***.***>, Mention ***@***.***>
Subject: Re: [epam/sap-commerce-intellij-idea-plugin] java.lang.NumberFormatException: For input string: "0-M308" (Issue #38)

Hello, @KakaWangSAP<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKakaWangSAP&data=04%7C01%7Ckaka.wang%40sap.com%7C71ef52f0f16946dfe4e808d9c651b1b2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637758876444725529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x6796jmRNwuGcWBOy0Dv4jmxLP0JNN5dsr8qatS9JNI%3D&reserved=0>, please provide the full version name of your SAP Commerce distributive

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fepam%2Fsap-commerce-intellij-idea-plugin%2Fissues%2F38%23issuecomment-1000507849&data=04%7C01%7Ckaka.wang%40sap.com%7C71ef52f0f16946dfe4e808d9c651b1b2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637758876444725529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ypSPszQaiVw8b%2F%2B%2FOqn%2BiCqPe2aO0Cu1OV2FrmTQ3Yw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMK7FAD4AFGE4T7EF2CXV2DUSOABTANCNFSM5HH4VHYA&data=04%7C01%7Ckaka.wang%40sap.com%7C71ef52f0f16946dfe4e808d9c651b1b2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637758876444735526%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kvibw%2BTiGTh0vdqKrxnWh%2Fb5yfuJ7lY9SsAjGkDIdUk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaka.wang%40sap.com%7C71ef52f0f16946dfe4e808d9c651b1b2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637758876444745516%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZULmGx3QpL9mQhMvAceu1qGmKdKnP5GN7xcjDC6agUo%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaka.wang%40sap.com%7C71ef52f0f16946dfe4e808d9c651b1b2%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637758876444745516%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YY%2BPG47XsDv%2BtQ6XnpkOijvZPyXApk5ZtqEZWL2ZL2o%3D&reserved=0>.
