### ISSUE TITLE
NoClassDefFoundError: org/jetbrains/idea/eclipse/EclipseProjectFinder

### ISSUE THREAD

**Issue by SaberBoutahar** [epam/sap-commerce-intellij-idea-plugin#43]
After installing the latest version of Intellij (2021.3) and updating the plugin, I have this error whenever I restart the IDE or perform a "refresh project" and the project structure is lost.
`java.lang.NoClassDefFoundError: org/jetbrains/idea/eclipse/EclipseProjectFinder
	at com.intellij.idea.plugin.hybris.project.descriptors.EclipseModuleDescriptor.findEclipseProjectName(EclipseModuleDescriptor.java:44)
	at com.intellij.idea.plugin.hybris.project.descriptors.EclipseModuleDescriptor.<init>(EclipseModuleDescriptor.java:40)
	at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisModuleDescriptorFactory.createDescriptor(DefaultHybrisModuleDescriptorFactory.java:103)
	at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.scanDirectoryForHybrisModules(DefaultHybrisProjectDescriptor.java:389)
	at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.setRootDirectoryAndScanForModules(DefaultHybrisProjectDescriptor.java:832)
	at com.intellij.idea.plugin.hybris.project.tasks.SearchModulesRootsTaskModalWindow.run(SearchModulesRootsTaskModalWindow.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:545)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:78)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.idea.eclipse.EclipseProjectFinder PluginClassLoader(plugin=PluginDescriptor(name=SAP Commerce Developers Toolset, id=com.intellij.idea.plugin.sap.commerce, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.1\plugins\SAP-Commerce-Developers-Toolset, version=2021.1, package=null), packagePrefix=null, instanceId=187, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 24 more`

**Comment by ghost** [comment]
Seems the issue was related to the IDEA SDK, and now 'refresh project' works correctly. If happens again - necessary to create a new issue.
