### ISSUE TITLE
Unable to import project in Intellij 2023.2 Community Version

### ISSUE THREAD

**Issue by sbasak-rccl** [epam/sap-commerce-intellij-idea-plugin#527]
I have downloaded Intellij 2023.2 Community Version in my new MAC M1 system. When I try to import the hybris project using Open from existing sources I see the project is not getting imported and the error is below. The plugin version is 2023.2.3

java.lang.ExceptionInInitializerError
	at com.intellij.idea.plugin.hybris.project.configurators.SpringConfigurator.<clinit>(SpringConfigurator.kt)
	at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultConfiguratorFactory.getSpringConfigurator(DefaultConfiguratorFactory.kt:35)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.run(ImportProjectProgressModalWindow.java:161)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: getApplication().getServ…Configurator::class.java) must not be null
	at com.intellij.idea.plugin.hybris.project.configurators.SpringConfigurator$Companion.<clinit>(SpringConfigurator.kt:46)
	... 26 more

**Comment by mlytvyn** [comment]
@sbasak-rccl , thank you for repoing, I'll fix it in scope of the next release. ~2 days

**Comment by mlytvyn** [comment]
@sbasak-rccl , fixed with https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/528

**Comment by mlytvyn** [comment]
@sbasak-rccl , can you please try latest `2023.2.5` version?

**Comment by mlytvyn** [comment]
@sbasak-rccl , I'll close this issue as resolved and confirmed in the  #526
