### ISSUE TITLE
Gradle plugin dependence is not enforced

### ISSUE THREAD

**Issue by balazsmiklos85** [epam/sap-commerce-intellij-idea-plugin#651]
### Background

I tend to disable IntelliJ plugins that are not needed in his project, to optimize memory usage. However, disabling the Gradle plugin causes that the "SAP Commerce Developers Toolset" plugin cannot start, because of exceptions like

```
com.intellij.diagnostic.PluginException: Cannot create class com.intellij.idea.plugin.hybris.flexibleSearch.file.actions.FlexibleSearchFileCreateAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=SAP Commerce Developers Toolset, id=com.intellij.idea.plugin.sap.commerce, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.2/plugins/SAP-Commerce-Developers-Toolset, version=2023.2.6, package=null, isBundled=false), packagePrefix=null, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1003)
	...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.idea.plugin.hybris.common.utils.HybrisIcons
	at com.intellij.idea.plugin.hybris.flexibleSearch.file.actions.FlexibleSearchFileCreateAction.<init>(FlexibleSearchFileCreateAction.java:43)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:962)
	... 66 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: icons/GradleIcons [in thread "Action Updater (Common)[ApplicationImpl pooled thread 3]"]
	at com.intellij.idea.plugin.hybris.common.utils.HybrisIcons.<clinit>(HybrisIcons.java:74)
	at com.intellij.idea.plugin.hybris.polyglotQuery.file.actions.PolyglotQueryFileCreateAction.<init>(PolyglotQueryFileCreateAction.kt:32)
	... 67 more
```
Enabling the Gradle plugin fixes this again. However, other plugins can somehow enforce their dependencies, for example if I would disable the "JakartaEE Platform" plugin, it warns me that it would also disable a list of other plugins, like the "Hibernate" plugin.

### Story

As a user, I would like to be warned when I disable a plugin that is needed by this plugin to run.

**Comment by mlytvyn** [comment]
@balazsmiklos85 , thank you for reporting this.

Due fact that Gradle plugin is an optional dependency disabling it does not warn user as it would be expected.

Adjusted in scope of the #652 , when Gradle plugin is disabled corresponding Configurator and resources will not be loaded

p.s. will be available in scope of the `2023.2.7`
