### ISSUE TITLE
Error when refreshing project

### ISSUE THREAD

**Issue by szzsa** [epam/sap-commerce-intellij-idea-plugin#653]
IDEA version: 2023.2.1
Plugin version: 2023.2.6
Stack Trace:
```
java.lang.IllegalStateException: @NotNull method com/intellij/idea/plugin/hybris/project/descriptors/DefaultHybrisProjectDescriptor.getPlatformHybrisModuleDescriptor must not return null
	at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.$$$reportNull$$$0(DefaultHybrisProjectDescriptor.java)
	at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.getPlatformHybrisModuleDescriptor(DefaultHybrisProjectDescriptor.java:856)
	at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultSpringConfigurator.process(DefaultSpringConfigurator.kt:68)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.run(ImportProjectProgressModalWindow.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mlytvyn** [comment]
@szzsa , can you please share project structure, what and how do you import?
what was the previous version of the IDEA and plugin?

**Comment by szzsa** [comment]
I have a CCV2 project and I reload project from the menu "Refresh SAP Commerce Project". This issue came up after updating IntelliJ IDEA to the latest version.

**Comment by mlytvyn** [comment]
@szzsa , could you please share the previous version of the IDEA and the plugin?

p.s. please try to re-import project from the scratch, there were some crucial API changes after 2023.2

**Comment by szzsa** [comment]
@mlytvyn I tried to import the project from scratch (even deleting idea module files and .idea folder) and got this error:
```
Can not configure Ant due to an error.
  
  java.lang.IllegalStateException: @NotNull method com/intellij/idea/plugin/hybris/project/descriptors/DefaultHybrisProjectDescriptor.getPlatformHybrisModuleDescriptor must not return null
at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.$$$reportNull$$$0(DefaultHybrisProjectDescriptor.java)
at com.intellij.idea.plugin.hybris.project.descriptors.DefaultHybrisProjectDescriptor.getPlatformHybrisModuleDescriptor(DefaultHybrisProjectDescriptor.java:856)
at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultAntConfigurator.parseModules(DefaultAntConfigurator.java:188)
at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultAntConfigurator.configure(DefaultAntConfigurator.java:154)
at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultPostImportConfigurator.finishImport(DefaultPostImportConfigurator.kt:62)
at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultPostImportConfigurator.configure$lambda$1(DefaultPostImportConfigurator.kt:43)
at com.intellij.openapi.project.SmartModeScheduler.runWhenSmart(SmartModeScheduler.kt:110)
at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.kt:200)
at com.intellij.idea.plugin.hybris.project.configurators.impl.DefaultPostImportConfigurator.configure(DefaultPostImportConfigurator.kt:42)
at com.intellij.idea.plugin.hybris.project.DefaultHybrisProjectImportBuilder.commit(DefaultHybrisProjectImportBuilder.java:168)
at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:50)
at com.intellij.idea.plugin.hybris.project.actions.ProjectRefreshAction.actionPerformed(ProjectRefreshAction.java:101)
at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:68)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:115)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:115)
at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
at java.desktop/java.awt.Component.processEvent(Component.java:6422)
at java.desktop/java.awt.Container.processEvent(Container.java:2266)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Previous version of IDEA is 2023.1.5, plugin 2023.2.5

**Comment by mlytvyn** [comment]
thanks, looks similar, looks like Platform is not found, may depend on project structure.

feel free to drop me a message in Slack -> https://github.com/epam/sap-commerce-intellij-idea-plugin

**Comment by mlytvyn** [comment]
@szzsa , ensure that correct SAP Commerce `platform` folder exists and that it contains `extensions.xml`
<img width="386" alt="image" src="https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/2292510/808c30ac-160b-4a93-b3ff-47266766d548">

**Comment by szzsa** [comment]
@mlytvyn The only difference is that I have hybris folder inside "core-customize".

**Comment by szzsa** [comment]
It worked. The solution is: Select hybris as project root directory when importing.

**Comment by thendricks0** [comment]
Same issue here, with 2023.2.5 it still works.

**Comment by mlytvyn** [comment]
@thendricks0 , can you share project structure? can be shared in Slack.

p.s. for few ccv2 project I have 2023.2.6 import works :(

**Comment by thendricks0** [comment]
It's a regular project structure, no ccv2 structure

`<gitroot>/hybris/bin/platform`

where the gitroot is the project source that is being imported.

**Comment by mlytvyn** [comment]
@thendricks0 , no clue what may be wrong. I'm not sure is it connected anyhow, but what is yours SAP Commerce version?

**Comment by szzsa** [comment]
@mlytvyn 
I am using:
SAP Commerce: 2205.2
OS: Windows 10

**Comment by mlytvyn** [comment]
@szzsa , @thendricks0 , not 100% sure, but it seems that I may know the root cause.
I'll request release of the  `2023.2.7` via EAP channel and I would like to ask you to grab it and manually install for verification before going live globally for everyone.

**Comment by szzsa** [comment]
Root cause of the issue identified:
"core-customize" folder contains a Gradle project which confuses the folder structure validation.
Fix coming soon.
@thendricks0 FYI

**Comment by mlytvyn** [comment]
@szzsa , @thendricks0 , requested release of the `2023.2.7`, thank you both for digging into it, together we can do anything!!!

p.s. please confirm once released and available

**Comment by szzsa** [comment]
@mlytvyn I can confirm, it works with the build from your latest changes on branch release/2023.2.7.

**Comment by mlytvyn** [comment]
@szzsa , @thendricks0 , version `2023.2.7` has been released https://plugins.jetbrains.com/plugin/12867-sap-commerce-developers-toolset/versions

I'm closing this ticket as resolved, thank you!

p.s. and don't forget to rate the Plugin :)
