### ISSUE TITLE
2023.2.9. NoClassDefFoundError

### ISSUE THREAD

**Issue by ghost** [epam/sap-commerce-intellij-idea-plugin#753]
Stack trace:

```
java.lang.NoClassDefFoundError: com/intellij/database/util/common/MapFun
at com.intellij.idea.plugin.hybris.system.type.meta.impl.TSMetaModelMergerImpl.merge(TSMetaModelMergerImpl.kt:85)
at com.intellij.idea.plugin.hybris.system.type.meta.impl.TSMetaModelAccessImpl.myGlobalMetaModelCache$lambda$6(TSMetaModelAccessImpl.kt:82)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
at com.intellij.idea.plugin.hybris.system.type.meta.impl.TSMetaModelAccessImpl$task$1.run$lambda$0(TSMetaModelAccessImpl.kt:100)
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$0(DumbService.kt:76)
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:117)
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:110)
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:76)
at com.intellij.idea.plugin.hybris.system.type.meta.impl.TSMetaModelAccessImpl$task$1.run(TSMetaModelAccessImpl.kt:92)
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.intellij.database.util.common.MapFun PluginClassLoader(plugin=PluginDescriptor(name=SAP Commerce Developers Toolset, id=com.intellij.idea.plugin.sap.commerce, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.2/plugins/SAP-Commerce-Developers-Toolset, version=2023.2.9, package=null, isBundled=false), packagePrefix=null, state=active)
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
... 41 more
```

**Comment by mlytvyn** [comment]
fixed
