### ISSUE TITLE
NPE during import after using JDK 17

### ISSUE THREAD

**Issue by khalid-sb** [epam/sap-commerce-intellij-idea-plugin#86]
after hybris upgrade to 2205, i should use JDK 17, when i try to import the project i get NPE and the project is not imported properly

```
java.lang.NullPointerException
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.selectSdk(ImportProjectProgressModalWindow.java:384)
	at com.intellij.idea.plugin.hybris.project.tasks.ImportProjectProgressModalWindow.run(ImportProjectProgressModalWindow.java:184)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
IntelliJ Version : 2019.2.4

**Comment by ghost** [comment]
Hi, @khalid-sb , could you, please, provide the next data to help us to investigate the issue:
1. IDE version
2. Plugin version

**Comment by khalid-sb** [comment]
> Hi, @khalid-sb , could you, please, provide the next data to help us to investigate the issue:
> 
>     1. IDE version
> 
>     2. Plugin version


Hi @mlytvyn ,

    IDE version : 2019.2.4
    Plugin version : 1908.4

**Comment by ghost** [comment]
@khalid-sb , It seems that the plugin version is quite old and doesn't support java 17. We recommend you update IDE and plugin versions to the latest ones to work with java 17.
