### ISSUE TITLE
IDE error when running FlexibleSearch query

### ISSUE THREAD

**Issue by balazsmiklos85** [epam/sap-commerce-intellij-idea-plugin#970]
When trying to run the query `select * from {BaseStore}` from IntelliJ with the SAP Commerce Developers Toolset (2023.3.4), I get the exception:
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 5037 path $.[7][30]
	at com.google.gson.Gson.fromJson(Gson.java:1241)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at com.intellij.idea.plugin.hybris.tools.remote.http.HybrisHacHttpClient.executeFlexibleSearch(HybrisHacHttpClient.java:196)
	at com.intellij.idea.plugin.hybris.tools.remote.console.impl.HybrisFlexibleSearchConsole.execute(HybrisFlexibleSearchConsole.kt:66)
	at com.intellij.idea.plugin.hybris.tools.remote.console.actions.handler.HybrisConsoleExecuteActionHandler$processLine$1$1.run(HybrisConsoleExecuteActionHandler.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 5037 path $.[7][30]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:485)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:122)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 33 more
```
with the plugin crash.

The same same query runs just fine from HAC, so I have no idea what may be special about this query.

**Comment by mlytvyn** [comment]
@balazsmiklos85 , it can be some data issue and Gson cannot parse it properly. I've just tried the same query locally and it works at my side.

Can you try to identify for which exact BaseStore and field you face this issue?

feel free to reach me out in the Project's Slack to share response.

**Comment by balazsmiklos85** [comment]
I'm also assuming it's a data problem, but I can't really figure out what might be wrong with my base stores, as the query works fine in HAC, but there it returns HTML, not JSON.

The main reason I opened this issue is that you may want to handle this more gracefully than crashing the plugin.

Also, I'm not aware of the project's Slack, I guess I'd have to be an Epam employee to access it.

**Comment by mlytvyn** [comment]
@balazsmiklos85 , I’ll add a “catch” and you can find a link in the Plugin’s readme.
This is an open source initiative and Slack channel is open for anyone :)

**Comment by mlytvyn** [comment]
@balazsmiklos85 , as requested - added exception handling https://github.com/epam/sap-commerce-intellij-idea-plugin/pull/976.

once you will identify data which causes an error feel free to drop a message in the Slack or here.
